server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.cloud.gateway: debug