server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: lb://PRODUCT-SERVICE
          predicates:
          - Path=/inventory/**


        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**



eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  endpoints:
    web:
      exposure:
        include: health,prometheus

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: debug