server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://postgres-userdb:5432/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: user-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:
    wait-time-in-ms-when-sync-empty: 0

springdoc:
  api-docs:
    path: /user-service/api-docs
    enabled: true
  swagger-ui:
    path: /user-service/swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    try-it-out-enabled: true
    filter: true

management:

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

