package com.productservice.exception.ErrorCode;


public enum ErrorCode {


    USER_ALREADY_DELETED,
    USER_ALREADY_EXISTS (  ),
    INVALID_REQUEST,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    INVENTORY_NOT_FOUND,
    INSUFFICIENT_INVENTORY_LEVEL,
    FORBIDDEN_OPERATION,
    PRODUCT_NOT_FOUND ,
    CONFLICT


}
